### ISSUE TITLE
Error while running trRosetta2

### ISSUE THREAD

**Issue by anu-bioinfo** [RosettaCommons/trRosetta2#13]
Hi,
I get this error while running the pipeline script. No PDB model is generated. Could you please help me out with this ?

Traceback (most recent call last):
  File "./get_embeddings.py", line 25, in <module>
    model = ProteinBertModel.from_pretrained('bert-base')
  File "/mnt/NewHDD/anaconda3/envs/casp14-baker/lib/python3.6/site-packages/tape/models/modeling_utils.py", line 470, in from_pretrained
    **kwargs
  File "/mnt/NewHDD/anaconda3/envs/casp14-baker/lib/python3.6/site-packages/tape/models/modeling_utils.py", line 172, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/mnt/NewHDD/anaconda3/envs/casp14-baker/lib/python3.6/site-packages/tape/models/modeling_utils.py", line 202, in from_json_file
    return cls.from_dict(json.loads(text))
  File "/mnt/NewHDD/anaconda3/envs/casp14-baker/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/mnt/NewHDD/anaconda3/envs/casp14-baker/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/mnt/NewHDD/anaconda3/envs/casp14-baker/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Best,

Anupam

**Comment by colinwprice** [comment]
I am having the same issues, I noticed the last update was around the same time this was posted. This seems like it's a part of the tape repo which hasn't changed recently. I've followed the install/demo example instructions from scratch a few times and it's always here where I get stuck.

**Comment by anu-bioinfo** [comment]
@colinwprice 
I too could not fix this. Now, I am running RoseTTaFold instead. Runs smoothly.

**Comment by Arielbs** [comment]
To fix this issue go to ./tape/get_embeddings.py 
Add to line 4: ProteinBertConfig
from tape import ProteinBertModel, TAPETokenizer, ProteinBertConfig

Than comment out line ~26:
#model = ProteinBertModel.from_pretrained('bert-base')
and add instead: 
config = ProteinBertConfig()
model = ProteinBertModel(config)

**Comment by GayatriNavle** [comment]
> To fix this issue go to ./tape/get_embeddings.py Add to line 4: ProteinBertConfig from tape import ProteinBertModel, TAPETokenizer, ProteinBertConfig
> 
> Than comment out line ~26: #model = ProteinBertModel.from_pretrained('bert-base') and add instead: config = ProteinBertConfig() model = ProteinBertModel(config)

Hi i tried this but i am still getting the same error 
can you suggest me an alternate

**Comment by KhodezaBegum** [comment]
I don't get this error anymore, but there is no model saved in example/T1078/model/
