### ISSUE TITLE
json.decoder issue 

### ISSUE THREAD

**Issue by GayatriNavle** [RosettaCommons/trRosetta2#15]
Generating TAPE features
243B [00:00, 284458.80B/s]
Traceback (most recent call last):
  File "/home/ngayatri/trRosetta2/trRosetta2/tape/get_embeddings.py", line 25, in <module>
    model = ProteinBertModel.from_pretrained('bert-base')
  File "/home/ngayatri/miniconda3/envs/casp14-baker/lib/python3.6/site-packages/tape/models/modeling_utils.py", line 470, in from_pretrained
    **kwargs
  File "/home/ngayatri/miniconda3/envs/casp14-baker/lib/python3.6/site-packages/tape/models/modeling_utils.py", line 172, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/home/ngayatri/miniconda3/envs/casp14-baker/lib/python3.6/site-packages/tape/models/modeling_utils.py", line 202, in from_json_file
    return cls.from_dict(json.loads(text))
  File "/home/ngayatri/miniconda3/envs/casp14-baker/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ngayatri/miniconda3/envs/casp14-baker/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ngayatri/miniconda3/envs/casp14-baker/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Running sequence-based trRosetta
Folding trRosetta models
Running trRefine
/home/ngayatri/trRosetta2/trRosetta2
Folding trRefine models
ls: cannot access /home/ngayatri/trRosetta2/trRosetta2/example/T1078/pdb-trRefine/model*.pdb: No such file or directory
Running DeepAccNet-msa on trRefine models

please help me solve this issue

**Comment by KhodezaBegum** [comment]
Following, I have the same issue.

**Comment by zero555666** [comment]
Following, I have the same issue.

**Comment by zero555666** [comment]
how to solve it ???

**Comment by yoavatsmonraz** [comment]
i also have it

**Comment by syy197** [comment]
pip install --upgrade tape-proteins
